### ISSUE TITLE
LeapMotionの情報取得

### ISSUE THREAD

**Issue by hirenjak** [hirenjak/KineFigu#4]

**Comment by ohyama-yuta** [comment]
大山がやってみます．

**Comment by hirenjak** [comment]
とりあえず根岸にグーパーの判定ができるように指のデータ取得やってもらったので、土曜に情報共有しながらクラスの作成してくれると楽になるかと

**Comment by YujiNegishi** [comment]
TestLeapMotion下に手の開閉データの取得出来るクラスを作成しました．
